### PR TITLE
Enable ldp:contains triples for indexing

### PR DESCRIPTION
**Pull request by awoods**
Related to: https://jira.duraspace.org/browse/FCREPO-1849

### CODE REVIEW

**Comment by acoburn** [comment]
I assume you realize the performance penalty of this for large repos, and that this change is really just for the convenience of testing and demos.

**Comment by awoods** [comment]
Yes. I assume the fcrepo4-vagrant setup is for testing and demos. See email...

**Comment by ajs6f** [comment]
No such remark appears in the README. If that is the case, it should be declared loud and proud.

**Comment by awoods** [comment]
The fcrepo4-vagrant can certainly be used in non-testing, non-demo scenarios. Just like with any Fedora installation, I think it is reasonable for users to configure their setup appropriately.
However, the default fcrepo4-vagrant should be tailored to showcasing functionality... like this PR is suggesting.

**Comment by ajs6f** [comment]
Then it should be so labelled.

**Comment by acoburn** [comment]
See the Readme https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/blob/master/fcrepo-indexing-triplestore/README.md

**Comment by awoods** [comment]
@acoburn :+1:

**Comment by ajs6f** [comment]
That README is totally unhelpful here and even misleading: "For instance, ldp:contains triples are excluded by default."

**Comment by awoods** [comment]
The comment is true, the "ldp:contains" is on by default in the fcrepo-camel-toolbox configuration. The fcrepo4-vagrant configuration is customized, however... in several ways.

What are you looking for here, @ajs6f ? If you have something you would like to see differently, please send a PR to this PR, otherwise, let's move it forward as is.

**Comment by ajs6f** [comment]
I don't think the purpose of the current PR is even obvious enough to me to do that. Move it ahead as you like.

**Comment by awoods** [comment]
Thanks, @ajs6f. Fundamentally, the purpose of this PR is to keep the fcrepo4-vagrant functionality the way it had also been before relatively recent ldp:contains filtering updates in fcrepo-camel-toolbox.

**Comment by awoods** [comment]
I believe it is in @acoburn's court. But if you have time, @ruebot, that would also be great.

**Comment by acoburn** [comment]
It's fine by me to make this change. My only concern is that people may look to the vagrant setup as a way to configure their production systems.

What you _should_ be doing is setting up fuseki with an owl reasoner such that you can pass in:

```
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX fedora: <http://fedora.info/definitions/v4/repository#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT {
  fedora:hasParent owl:inverseOf ldp:contains . 
} WHERE {}
```

Then you'll have your cake and eat it too, meaning you'll get all the `ldp:contains` triples without having to send them over the wire. Basically, the question I have is this: is the vagrant system just for testing and running demos or does it imply some type of "typical setup". Either way, my money is on using a reasoner.

**Comment by acoburn** [comment]
@awoods you know about my troubled relationship with vagrant. I'd leave the testing to @ruebot

**Comment by awoods** [comment]
@acoburn, it looks like setting up an OWL reasoner with Fuseki will require a fair amount of configuration and testing:
http://baach.de/Members/jhb/getting-started-with-jena-fuseki-and-owl-reasoning

I would not be inclined to slip that in at the last minute before the 4.5.1 release. However, I do think it is important that the 4.5.1 fcrepo4-vagrant work as it has in the past. Actually, the workshops that we do at least once a month rely on that.

I would suggest we keep the previous functionality in this release (by merging this PR) and create a new ticket to include reasoning in Fuseki for the next round.

**Comment by acoburn** [comment]
@awoods that makes sense to me. Can you create a ticket related to adding a reasoner to the fuseki config and assign it to me?

**Comment by awoods** [comment]
@acoburn: https://jira.duraspace.org/browse/FCREPO-2006

**Pull request merged**
