### PR TITLE
Misspelled fcrepo-ldpath feature name.

### PR DESCRIPTION
**Pull request by whikloj**
Addresses [FCREPO-2256](https://jira.duraspace.org/browse/FCREPO-2256)

### CODE REVIEW

**Comment by whikloj** [comment]
Yeah, I wasn't sure about that, but I'll put one in.

**Comment by whikloj** [comment]
Hmm no that shouldn't happen, I didn't see that. Maybe my eyes are going. Hold off for a bit.

**Comment by acoburn** [comment]
`fcrepo-ldpath` is now installed when `fcrepo-indexing-solr` is installed.

**Comment by whikloj** [comment]
@ruebot I was off in la-la land with the feature naming here. This should remove that message.

**Pull request merged**
